### PR TITLE
From tar to bzip in 'Adding new language' section

### PR DESCRIPTION
**Pull request by pr3ssh**

### CODE REVIEW

**Comment by fsondej** [comment]
What is better about bzip?

**Comment by pr3ssh** [comment]
To me, this **_tar_** command does not work properly when trying to uncompress bzip file.

**Comment by fsondej** [comment]
Just checked it, and you're right, tar doesn't work.
Thanks!

**Comment by pr3ssh** [comment]
Im gonna create this PR on a new repo.

**Pull request closed without merging**
